DiDongOnline/Controllers/DiDongOnlineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DiDongOnline.Models;
using PagedList;
using PagedList.Mvc;

namespace DiDongOnline.Controllers
{
    public class DiDongOnlineController : Controller
    {
        dbDiDongOnlineDataContext db = new dbDiDongOnlineDataContext();
        // GET: DiDongOnline
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult HeaderPartial()
        {
            return PartialView();
        }
        public ActionResult FooterPartial()
        {
            return PartialView();
        }
        public ActionResult ProductsTypePartial()
        {
            var listLoaiSanPham = from lsp in db.LOAISANPHAMs select lsp;
            return PartialView(listLoaiSanPham);
        }
        public ActionResult ProductsType(int id, int? page)
        {
            ViewBag.MaLoaiSP = id;
            int iSize = 6;
            int iPageNum = (page ?? 1);
            var sp = from s in db.SANPHAMs where s.MaLoaiSP == id select s;
            return View(sp.ToPagedList(iPageNum, iSize));
        }
        public ActionResult LoginLogout()
        {
            return PartialView("LoginLogoutPartial");
        }
        public ActionResult SaleProductsPartial()
        {
            return PartialView();
        }
        private List<SANPHAM> SellingProducts(int count)
        {
            return db.SANPHAMs.OrderByDescending(a => a.SoLuongBan).Take(count).ToList();
        }
        public ActionResult SellingProducts()
        {
            var listSellingProducts = SellingProducts(4);
            return PartialView(listSellingProducts);
        }
        private List<SANPHAM> NewProducts(int count)
        {
            return db.SANPHAMs.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        public ActionResult NewProducts()
        {
            var listNewProducts = NewProducts(4);
            return PartialView(listNewProducts);
        }
        public ActionResult AllProducts( int? page)
        {
            int iSize = 8;
            int iPageNum = (page ?? 1);;
            var lstAllProducts = NewProducts(int.MaxValue);
            return View(lstAllProducts.ToPagedList(iPageNum, iSize));
        }
        [HttpGet]
        public ActionResult Search(int? page, string sTuKhoa)
        {
            if (sTuKhoa == "")
            {
                return View("Index");
            }
            ViewBag.TuKhoa = sTuKhoa;
            int iSize = 8;
            int iPageNum = (page ?? 1);
            var lstSp = db.SANPHAMs.Where(n => n.TenSanPham.ToUpper().Contains(sTuKhoa.ToUpper()));
            return View(lstSp.OrderBy(n => n.TenSanPham).ToPagedList(iPageNum, iSize));
        }
        [HttpPost]
        public ActionResult LayTuKhoa(string sTuKhoa)
        {
            return RedirectToAction("Search", new { @sTuKhoa = sTuKhoa });
        }
        public ActionResult ProductsDetail(int id)
        {
            var sp = from s in db.SANPHAMs where s.MaSanPham == id select s;
            return View(sp.Single());
        }
    }
}

DiDongOnline/Views/Shared/FooterPartial.cshtml
<div class="footer">    <div class="wrap">
        <div class="section group">
            <div class="col_1_of_4 span_1_of_4">
                <h4>Thông tin</h4>
                <ul>
                    <li><a href="about.html">Giới thiệu</a></li>
                    <li><a href="contact.html">Dịch vụ</a></li>
                    <li><a href="#">Tìm kiếm nâng cao</a></li>
                    <li><a href="delivery.html">Giao Hàng và Thanh Toán</a></li>
                    <li><a href="contact.html">Chính sách bảo hành và đổi trả</a></li>
                </ul>
            </div>
            <div class="col_1_of_4 span_1_of_4">
                <h4>My account</h4>
                <ul>
                    <li><a href="~/User/DangNhap">Đăng nhập</a></li>
                    <li><a href="~/GioHang/GioHang">Xem giỏ hàng</a></li>
                    <li><a href="#">Sản phẩm yêu thích</a></li>
                    <li><a href="#">Theo dõi đơn hàng của tôi</a></li>
                    <li><a href="contact.html">Hỗ trợ</a></li>
                </ul>
            </div>
            <div class="col_1_of_4 span_1_of_4">
                <h4>Tổng đài hỗ trợ (Miễn phí gọi)</h4>
                <ul>
                    <li><span>+84-962-293112</span></li>
                </ul>
                <div class="social-icons">
                    <h4>Theo dỗi chúng tôi</h4>
                    <ul>
                        <li><a href="#" target="_blank"><img src="~/images/facebook.png" alt="" /></a></li>
                        <li><a href="#" target="_blank"><img src="~/images/twitter.png" alt="" /></a></li>
                        <li><a href="#" target="_blank"><img src="~/images/skype.png" alt="" /> </a></li>
                        <li><a href="#" target="_blank"> <img src="~/images/dribbble.png" alt="" /></a></li>
                        <li><a href="#" target="_blank"> <img src="~/images/linkedin.png" alt="" /></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="copy_right">
        <p>&copy; 2022 Home_Shoppe. All rights reserved | Design by <a href="#">Phan Minh Huy</a></p>
    </div>
</div>

DiDongOnline/Views/Shared/HeaderPartial.cshtml
<div class="header">
    <div class="headertop_desc">
        <div class="call">
            <p><span>2024801030124@student.tdmu.edu.vn</span></p>
        </div>
        <div class="account_desc">
            <ul>
                @Html.Action("LoginLogout", "DiDongOnline")
            </ul>
        </div>
        <div class="clear"></div>
    </div>
    <div class="header_top">
        <div class="logo">
            <a href="index.html"><img src="~/images/logo.png" alt="" /></a>
        </div>
        <div class="cart">
            <p>
                @Html.Action("GioHangPartial", "GioHang")
            </p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="header_bottom">
        <div class="menu">
            <ul>
                <li class="active"><a href="~/DiDongOnline/Index">Trang chủ</a></li>
                <li><a href="~/DiDongOnline/AllProducts">Tất cả sản phẩm</a></li>
                <li><a href="news.html">Tin tức</a></li>
            </ul>
        </div>
        <div class="search_box">
            @using (Html.BeginForm("LayTuKhoa", "DiDongOnline"))
            {
                <form>
                    <input type="text" name="sTuKhoa" class="form-control" placeholder="Tìm kiếm">
                    <button type="submit" class="btn btn-default">Tìm</button>
                </form>
            }

        </div>
        <div class="clear"></div>
    </div>
    <div class="header_slide">
        @Html.Action("ProductsTypePartial", "DiDongOnline")
        @Html.Action("SaleProductsPartial", "DiDongOnline")

        <div class="clear"></div>
    </div>
</div>

DiDongOnline/Views/Shared/ProductsTypePartial.cshtml
@model IEnumerable<DiDongOnline.Models.LOAISANPHAM>
<div class="header_bottom_left">
    <div class="categories">
        <ul>
            <h3>Loại Sản Phẩm</h3>
            @foreach (var item in Model)
            {
                <li><a href="@Url.Action("ProductsType","DiDongOnline", new {id = item.MaLoaiSP})" class="list-group-item"> @item.TenLoaiSP</a></li>
            }
        </ul>
    </div>
</div>

DiDongOnline/Views/Shared/SaleProductsPartial.cshtml
<div class="header_bottom_right">
    <div class="slider">
        <div id="slider">
            <div id="mover">
                <div id="slide-1" class="slide">
                    <div class="slider-img">
                        <a href="preview.html"><img src="~/images/slide-1-image.png" alt="learn more" /></a>
                    </div>
                    <div class="slider-text">
                        <h1>Clearance<br><span>Giảm giá</span></h1>
                        <h2>Lên đến 20%</h2>
                        <div class="features_list">
                            <h4>Get to Know More About Our Memorable Services Lorem Ipsum is simply dummy text</h4>
                        </div>
                        <a href="preview.html" class="button">Mua ngay</a>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="slide">
                    <div class="slider-text">
                        <h1>Clearance<br><span>Giảm giá</span></h1>
                        <h2>Lên đến 40%</h2>
                        <div class="features_list">
                            <h4>Get to Know More About Our Memorable Services</h4>
                        </div>
                        <a href="preview.html" class="button">Mua ngay</a>
                    </div>
                    <div class="slider-img">
                        <a href="preview.html"><img src="~/images/slide-3-image.jpg" alt="learn more" /></a>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="slide">
                    <div class="slider-img">
                        <a href="preview.html"><img src="~/images/slide-2-image.jpg" alt="learn more" /></a>
                    </div>
                    <div class="slider-text">
                        <h1>Clearance<br><span>Giảm giá</span></h1>
                        <h2>Lên đến 10%</h2>
                        <div class="features_list">
                            <h4>Get to Know More About Our Memorable Services Lorem Ipsum is simply dummy text</h4>
                        </div>
                        <a href="preview.html" class="button">Mua ngay</a>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>

DiDongOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DiDongOnline/Views/Shared/_LayoutUser.cshtml
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

    <title>Free Home Shoppe Website Template | Home </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="~/FileContent/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/FileContent/css/slider.css" rel="stylesheet" type="text/css" media="all" />

    <script type="text/javascript" src="~/FileContent/js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="~/FileContent/js/move-top.js"></script>
    <script type="text/javascript" src="~/FileContent/js/easing.js"></script>
    <script type="text/javascript" src="~/FileContent/js/startstop-slider.js"></script>

</head>
<body>
    <div class="wrap">
        @Html.Action("HeaderPartial", "DiDongOnline")
        @RenderBody()
    </div>
    @Html.Action("FooterPartial", "DiDongOnline")
    <script type="text/javascript">
		$(document).ready(function() {
			$().UItoTop({ easingType: 'easeOutQuart' });

		});
    </script>
    <a href="#" id="toTop"><span id="toTopHover"> </span></a>
</body>
</html>